### ISSUE TITLE
Add support for GUID keys

### ISSUE THREAD

**Issue by dwerner** [dwerner/dorm#1]
We need support for GUID keys

**Comment by dwerner** [comment]
Dialect needs support for GUID datatype (new fieldtype based on PrimaryKeyField)

**Comment by haddow777** [comment]
To support GUID's, Dorm will need to have more than just the save functions, since every record inserted will always have a GUID id field. 
It will probably be easier if there is an insert specific function so Dorm will always know that the record is being inserted. The same will need to go for updates, at least so an update can take place for select fields of a record so non updated fields won't be blown away.

**Comment by haddow777** [comment]
I have committed an update for this functionality. Currently the changes allow for a uuid field for primary key. The new field currently is PrimaryKeyUuidField and there are two new functions in dorm: insert and update. The libraries ability to handle uuid's has been tested for the following functions: createTable, insert, and dropTable. Those tests are currently passing without issue.

**Comment by haddow777** [comment]
Seems I found a bug with the uuid code. When attempting to test the functions get and update, I found that they were not working correctly. It seems that trying to include the uuid value in a where clause is causing the issue. In the get function, it simply doesn't put the where clause making it automatically a global select statement. The update function simply fails as the where clause is added, but fails.

I am attempting to figure out the core issue here.

**Comment by haddow777** [comment]
Found out the issue with the update function finally. It seems that the uuid needs to be wrapped in single quotes in the where clause of the SQL statement. I had problems as I was trying for a while to use double quotes, but that doesn't work. It has to be single quotes. 

So, the update now works in my local copy. I am going to move onto the get function and see why the where clause is completely missing from its SQL statement.

**Comment by haddow777** [comment]
Okay, I think I fixed the get where problem with uuid's. If only a uuid, which in javascript is a string, was passed through the get() functions parameter, it was being ignored. In the get() function, it only checked for a number value, so I added the ability for it to take into account a string value. In this way, the uuid now gets converted into a proper where object, which in turn gets converted into the where clause of the SQL statement.

Things are looking good uuid wise.

**Comment by haddow777** [comment]
Tried to push the changes up, but there was a merge conflict. I will do it later.

**Comment by haddow777** [comment]
It has now been merged, tested, and pushed up to Github.

**Comment by dwerner** [comment]
Closing this issue then.
