### ISSUE TITLE
Update throws an error when I try to assign a value to the primary key

### ISSUE THREAD

**Issue by haddow777** [dwerner/dorm#4]
I have been attempting to work with the update side of dorm and I ran into an issue. From what I understand, to update, I need to create an object using its entity. Then, when I save that object, the save function will determine if the save should be an SQL INSERT or UPDATE depending on whether an id has been supplied or not.

The problem I am having though, is that the verification code throws an error anytime I assign a value to the primary key as it is set to not-modifiable. To get around this issue, i have had to set the primary key as modifiable in the Fields.js file temporarily until this gets fixed.

**Comment by dwerner** [comment]
You can get around this by doing something like 

Entity.values[Entity.identifier] = 'some value here'

This goes around the ES5 property functions wrapping the value, but isn't recommended when using DB generated PKs. I guess we could add a special case for UUIDs, if I'm understanding that you want this for that use case.

**Comment by haddow777** [comment]
Actually, this issue didn't have anything to do with my uuid code. This happened in the normal code. The uuid code had the not-modifiable flag turned off anyways as in that case I would be supplying the id whether is was an INSERT or an UPDATE.

I think the problem is that the verification code doesn't know whether the save is for an update or an insert. It is most likely the wrong spot to be checking this value. I think that it needs to allow the assignment even if the value is non-modifiable. Then, if an insert is being generated, have the buildInsertQuery function check to see if the value is not-modifiable and throw the error if a value is assigned to it.

In that case, if an update is being generated, the id is supplied and no error is thrown.

**Comment by dwerner** [comment]
I think the reason I included that code to prevent manual assignment was just my over-defensive programming at play. The whole notion of assigning a PK value may well have merit, and perhaps it would be simpler and better just to trust that the consuming code does the right thing in their use case. I'll take a look and rip out that prevention stuff.

**Comment by dwerner** [comment]
I've removed the notion of preventing assignment of PKs. Closing this one.
